apiVersion: v1
data:
  database: cG9zdGdyZXM=
  host: dGNwLnRhcy52bXRhbnp1LmNvbQ==
  password: YzRCNUQzOVg4MGZFZzJuQzZxMTc=
  port: MTAyNg== # 1026
  provider: dGFzcG9zdGdyZXNxbA==  # tas
  type: cG9zdGdyZXNxbAo= # postgresql
  username: cGdhZG1pbg== # pgadmin
kind: Secret
metadata:
  name: pgvector-creds
type: servicebinding.io/postgresql

---
apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: pgvector
spec:
  bindingConnectors:
  - name: main
    description: Posgres pgvector service for AI use cases
    type: postgresql
    secretRef:
      name: pgvector-creds